import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: "doc",
      id: "index",
      label: "Catalogue",
    },
    {
      type: "category",
      label: "Grammar",
      items: [
        {
          type: "autogenerated",
          dirName: "grammar",
        },
      ],
    },
    {
      type: "category",
      label: "Words & Phrases",
      items: [
        {
          type: "autogenerated",
          dirName: "words_phrases",
        },
      ],
    },
    {
      type: "category",
      label: "Pronunciation",
      items: [
        {
          type: "autogenerated",
          dirName: "pronunciation",
        },
      ],
    },
  ],
};

export default sidebars;
